#!/usr/bin/env python

import click
import json
import lib
import shutil

@click.command()
@click.argument('json_file', nargs=1)
@click.argument('keys', nargs=-1)
@click.argument('output', nargs=1)
def take(json_file, output, keys=[]):
    with open(json_file) as f:
        data = json.load(f)
    d = {}
    for key in keys:
        if key not in data:
            print "did you mis-spell", key, "?"
        d[key] = data.get(key, None)


    with open(output, 'w') as f:
        json.dump(d, f)




if __name__=="__main__":
    take()
